blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.create_post, name='create_post'),
    path('<int:post_id>/edit/', views.edit_post, name='edit_post'),
    path('<int:post_id>/comment/', views.post_comment, name='post_comment'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from core import settings

from django.contrib.auth import views as auth_views

urlpatterns = [
    path("admin/", admin.site.urls),
    path('accounts/', include('accounts.urls')),

    # Password Change
    path('password_change', 
         auth_views.PasswordChangeView.as_view(),
         name='password_change'),
    path('password_change/done',
         auth_views.PasswordChangeDoneView.as_view(),
         name='password_change_done'),

    # Password Reset
    path('password_reset/',
         auth_views.PasswordResetView.as_view(),
         name='password_reset'),
    path('password_reset/done',
         auth_views.PasswordResetDoneView.as_view(),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('reset_done/',
         auth_views.PasswordResetCompleteView.as_view(),
         name='password_reset_complete'),
    
    path('', include('matrimony.urls')),
    path('blog/', include('blog.urls'))


    ]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

matrimony/urls.py
from django.urls import path
from . import views

app_name= 'matrimony'

urlpatterns = [
    path('', views.ProfileListView, name='profile_list'),
    path('<int:profile_id>', views.ProfileDetailView, name='profile_detail'),
    path('<int:profile_id>/delete', views.ProfileDeleteView, name='profile_delete'),
    path('contact', views.ContactView, name='contact'),
    path('new_profile', views.NewProfileView, name='new_profile')
]

# 127.0.0.1:8000/

matrimony/models.py
from django.db import models
from django.core.files.storage import FileSystemStorage
from django.conf import settings

fs = FileSystemStorage(location=settings.MEDIA_ROOT)

# Create your models here.

class Religion(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Sect(models.Model):
    name = models.CharField(max_length=100)
    religion = models.ForeignKey(Religion, on_delete=models.CASCADE, related_name='sects')
    def __str__(self):
        return self.name
    
class Caste(models.Model):
    name = models.CharField(max_length=100)
    def __str__(self):
        return self.name

class Hobbies(models.Model):
    name = models.CharField(max_length=100)

    class Meta:
        verbose_name_plural= 'Hobbies'

    def __str__(self):
        return self.name
    
class FatherProfile(models.Model):
    name = models.CharField(max_length=100)
    occupation = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Profile(models.Model):
    GENDER_CHOICES = [('M', 'Male'), ('F', 'Female')]
    name= models.CharField(max_length=100, default='Unnamed')
    profile_pic=models.ImageField(null=True, blank=True)
    age=models.IntegerField()
    gender=models.CharField(max_length=1, choices=GENDER_CHOICES)
    occupation=models.CharField(max_length=100, null=True, blank=True)
    birth_date=models.DateField(null=True)
    is_married=models.BooleanField(default=False)
    email=models.EmailField(unique=True)

    religion= models.ForeignKey(Religion, on_delete= models.CASCADE, related_name='profiles', null=True)
    sect= models.ForeignKey(Sect, on_delete= models.CASCADE, related_name='profiles', null=True)
    caste= models.ForeignKey(Caste, on_delete= models.CASCADE, related_name='profiles', null=True)
    hobbies = models.ManyToManyField(Hobbies, related_name='profiles', null=True)
    father = models.OneToOneField(FatherProfile, on_delete= models.CASCADE, related_name='dependent', null=True)

    def __str__(self):
        return self.name
    
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        print(f'Data Updated for {self.name}')

matrimony/forms.py
from django import forms

from django.core.validators import EmailValidator
from django.core.exceptions import ValidationError

from .models import Profile

def my_email_validator(email):
    if email.split('@')[1].split('.')[0].lower() == 'hotmail':
        raise ValidationError("Email Not Acceptable")

class ContactForm(forms.Form):
    name = forms.CharField(max_length=100)
    email = forms.CharField(validators=[EmailValidator(),my_email_validator])
    verify_email = forms.CharField()
    message = forms.CharField(widget=forms.Textarea)

    def clean(self):
        cleaned_data = super().clean()
        if cleaned_data.get('email') != cleaned_data.get('verify_email'):
            raise forms.ValidationError("Email Mismatch")
        return cleaned_data
        
class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = "__all__"

matrimony/views.py
from django.shortcuts import redirect, render
from .models import Profile
from .forms import ContactForm, ProfileForm
from django.contrib.auth.decorators import login_required

# Create your views here.

def ProfileListView(request):
    profiles= Profile.objects.all()
    user = request.user
    return render(request, 'matrimony/profile_list.html', {'profiles': profiles, 'user': user})

def ProfileDetailView(request, profile_id):
    profile= Profile.objects.get(id=profile_id)
    user = request.user
    return render(request, 'matrimony/profile_detail.html', {'profile':profile, 'user': user})

def ProfileDeleteView(request, profile_id):
    profile=Profile.objects.get(id=profile_id)
    profile.delete()
    profiles = Profile.objects.all()
    return redirect('matrimony:profile_list')

def ContactView(request):

    if request.method == 'POST':
        form = ContactForm(request.POST)

        if form.is_valid():
            print(f"NAME: {form.cleaned_data['name']}")
            print(f"Email: {form.cleaned_data['email']}")
            print(f"Message: {form.cleaned_data['message']}")

    else:
        form = ContactForm()
    user = request.user
    return render(request, 'matrimony/contact.html', {'form':form, 'user':user})

@login_required
def NewProfileView(request):
    if request.method == 'POST':
        form = ProfileForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('matrimony:profile_list')

    else:
        form = ProfileForm()

    return render(request, 'matrimony/new_profile.html', {'form':form})

matrimony/templates/matrimony/contact.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Contact Us{% endblock title %}

{% block content %}
<form method='post'>
    <div class="form-group">
        {{form.name.label_tag}}
        <input type="text" class='form-control' name="{{form.name.name}}">
    </div>
    <div class="form-group">
        {{form.email.label_tag}}
        <input type="email" class='form-control' name="{{form.email.name}}">

    </div>
    <div class="form-group">
        {{form.verify_email.label_tag}}
        <input type="email" class='form-control' name="{{form.verify_email.name}}">

    </div>
    <div class="form-group">
        {{form.message.label_tag}}
        <textarea class='form-control' name="{{form.message.name}}"></textarea>

    </div>

    {% csrf_token %}

    <input type="submit" class='btn btn-primary' value='Submit'>
</form>
{% endblock  %}

matrimony/templates/matrimony/new_profile.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <h1>Add a New Profile</h1>
    <form method="post" enctype="multipart/form-data">
        {{form.as_p}}
        {% csrf_token %}
        <input type="submit" class='btn btn-primary' value="Submit">
    </form>
{% endblock content %}

matrimony/templates/matrimony/profile_detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container mt-5">
    <div class="row">
        <div class="col-md-8 offset-md-2">
            <div class="card">
                <div class="row no-gutters">
                    <div class="col-md-4">
                        <img src="{{ profile.profile_pic.url }}" class="card-img" alt="Profile picture">
                    </div>
                    <div class="col-md-8">
                        <div class="card-body">
                            <h5 class="card-title">{{ profile.name }}</h5>
                            <p class="card-text"><small class="text-muted">{{ profile.age }} years old</small></p>
                            <p class="card-text">{{ profile.bio }}</p>
                            <p class="card-text">
                                <strong>Occupation:</strong> {{ profile.occupation }}<br>
                                <strong>Date of Birth:</strong> {{ profile.birth_date }}<br>
                                <strong>Marital Status:</strong> {{ profile.is_married|yesno:"Married,Single" }}<br>
                                <strong>Email:</strong> {{ profile.email }}<br>
                                <strong>Religion</strong> {{ profile.religion }}<br>
                                <strong>Sect</strong> {{ profile.sect }}<br>
                                <strong>Caste</strong> {{ profile.caste }}<br>
                                <strong>Hobbies</strong>
                                    <ul>
                                        {% for hobby in profile.hobbies.all %}
                                            <li>{{hobby}}</li>
                                        {% endfor %}
                                    </ul>
                                <br>
                                <strong>Father's Name</strong> {{ profile.father.name }}<br>
                                <strong>Father's Occupation</strong> {{ profile.father.occupation }}<br>

                            </p>
                            <a href="{% url 'matrimony:profile_list' %}" class="btn btn-primary">Back</a>
                            <a href="{% url 'matrimony:profile_delete' profile.id %}" class="btn btn-danger">Delete</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

matrimony/templates/matrimony/profile_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


<div class="container">
    <a href="{% url 'matrimony:new_profile' %}" class="btn btn-warning">Add  Profile</a>

    <br>
    <div class="row">
        {% for profile in profiles %}
        <div class="col-md-4">
            <div class="card">
                <img class="card-img-top" src="{{ profile.profile_pic.url }}" alt="Profile picture" width="300" height="400">
                <div class="card-body">
                    <h5 class="card-title">{{ profile.name }}</h5>
                    <a href="{% url 'matrimony:profile_detail' profile.id %}" class="btn btn-primary">View Profile</a>
                </div>
            </div>
            <p></p>
        </div>


        {% endfor %}
    </div>
</div>
{% endblock %}