accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('register/', views.RegisterView, name="register"),
    path('login/', views.LoginView, name="login"),
    path('logout/', views.LogoutView, name='logout'),
    path('delete/', views.DeleteView, name='delete'),
    path('verify_email/<str:token>', views.verify_email_view, name='verify_email_view')
]

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.create_post, name='create_post'),
    path('<int:post_id>/edit/', views.edit_post, name='edit_post'),
    path('<int:post_id>/comment/', views.post_comment, name='post_comment'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from core import settings

from django.contrib.auth import views as auth_views

urlpatterns = [
    path("admin/", admin.site.urls),
    path('accounts/', include('accounts.urls')),

    # Password Change
    path('password_change', 
         auth_views.PasswordChangeView.as_view(),
         name='password_change'),
    path('password_change/done',
         auth_views.PasswordChangeDoneView.as_view(),
         name='password_change_done'),

    # Password Reset
    path('password_reset/',
         auth_views.PasswordResetView.as_view(),
         name='password_reset'),
    path('password_reset/done',
         auth_views.PasswordResetDoneView.as_view(),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('reset_done/',
         auth_views.PasswordResetCompleteView.as_view(),
         name='password_reset_complete'),
    
    path('', include('matrimony.urls')),
    path('blog/', include('blog.urls'))


    ]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

matrimony/urls.py
from django.urls import path
from . import views

app_name= 'matrimony'

urlpatterns = [
    path('', views.ProfileListView, name='profile_list'),
    path('<int:profile_id>', views.ProfileDetailView, name='profile_detail'),
    path('<int:profile_id>/delete', views.ProfileDeleteView, name='profile_delete'),
    path('contact', views.ContactView, name='contact'),
    path('new_profile', views.NewProfileView, name='new_profile')
]

# 127.0.0.1:8000/

templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <!-- Load Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="{%static 'matrimony/css/styles.css'%}">
    <title>Matrimonial App</title>
</head>
<body>
    {% include 'header.html' %}

    <p></p>
    
    <main role="main" class="container">
        {% block content %}{% endblock %}
    </main>

    {% include 'footer.html' %}
    
    <!-- Load Bootstrap JS -->
    {% comment %} <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script> {% endcomment %}
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
</body>
</html>

templates/footer.html
<!-- templates/footer.html -->

<footer class="footer bg-dark mt-5 fixed-bottom">
    <div class="container">
      <span class="text-muted text-center d-block">© 2023 Matrimonial App</span>
    </div>
  </footer>
  

templates/header.html
<!-- templates/header.html -->
{% load static %}


<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="#"><img src="{% static 'images/logo.png' %}" width="30px" alt="">Matrimonial App</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'matrimony:profile_list' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'matrimony:contact' %}">Contact Us</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'blog:post_list' %}">Our Blog</a>
        </li>
        </ul>
        {% if user.is_authenticated %}
        <ul id='logged-in' class="navbar-nav ml-auto">
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" role="button" data-toggle="dropdown"  href="{% url 'password_change' %}">{{user.username}}</a>
            <div class="dropdown-menu dropdown-menu-right">
              <a class="dropdown-item" href="{% url 'password_change' %}">Change Password</a>
              <a class="dropdown-item" href="{% url 'accounts:delete' %}">Delete Account</a>
              <a class="dropdown-item" id='logout-btn' href="{% url 'accounts:logout' %}">Logout</a>
            </div>
          </li>
        </ul>
        {% endif %}
        <!-- Add more links as needed -->
      
    </div>
  </nav>

  <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
  <script> var csrfToken = '{{csrf_token}}' </script>
  <script src="{% static 'js/header.js' %}"></script>